### ISSUE TITLE
Difference between this and the native conditional row?

### ISSUE THREAD

**Issue by Fabenissimo** [bratanon/lovelace-conditional-entity-row#2]
Hi,

as the title already says it, what’s the difference to the native method? What’s the benefit of yours?

Fabian

**Comment by bratanon** [comment]
This is per entity and not per card.

**Comment by Fabenissimo** [comment]
That’s what i meant: https://www.home-assistant.io/lovelace/entities/#conditional

**Comment by bratanon** [comment]
The native one is for cards. To hide and show whole cards. Mine is for entities within a card and not the card itself.

**Comment by pejotigrek** [comment]
so it's more like [entity filter card](https://www.home-assistant.io/lovelace/entity-filter/)?

**Comment by Fabenissimo** [comment]
@pejotigrek I don’t see any difference in what this custom card does and the native method I posted above. Again, maybe I’m missing the point. My link does not go to the conditional “card” but rather to the special entity row for the entities card, where you can set conditions for an entity row in the entities card. You basically can show/hide entities in the entities card based on a condition that you specify.

**Comment by pejotigrek** [comment]
> @pejotigrek I don’t see any difference in what this custom card does and the native method I posted above. Again, maybe I’m missing the point. My link does not go to the conditional “card” but rather to the special entity row for the entities card, where you can set conditions for an entity row in the entities card. You basically can show/hide entities in the entities card based on a condition that you specify.

hey, I'm on the same page as you - not entirely understanding what is the purpose of the card, especially that the name is VERY confusing and IMHO should be differentiated from the original ones. so my question was meant to @bratanon mostly ;)

[if we assume, that you can enter more entities into config of the card that you've mentioned - then sure, condition could hide whole card and **branaton** is _kinda_ right, but then you can use entity filter card I've mentioned, just to show entities with specific condition, and this lovelace-conditional-entity-row card renders obsolete and unnecessary duplicate.. but maybe there is something that we both can't see.. ;)]

**Comment by bratanon** [comment]
Both your links are talking about this on the card level. 

`state_filter` is for all entities within the card.
`conditions` are for a whole card.

What if you only what this filter for 1/5 entities in a card?
This plugin is **NOT for cards**. Its an **entity row** plugin.

**Comment by bratanon** [comment]
Well, I now tested the `- type: conditional` and yes, that brings the same effect.

This card is deprecated I guess.
